### ISSUE TITLE
Unix theme doesnt works

### ISSUE THREAD

**Issue by ZombieBro2044** [Humpol/pt-themes#1]
Its gives 500 server error after theme installion

**Comment by Wallvon** [comment]
Considering that it is a paid theme and it shouldn't be on GitHub in the first place that is not really that surprising.

**Comment by VnKyYey** [comment]
how to fix it?

**Comment by ZombieBro2044** [comment]
Well I just brought it from pterodactyl market. you can't use this script for unix theme on pterodactyl panel current version.
